[tool.ruff]
line-length = 79
lint.ignore = []
lint.select = [
    "A",
    "D",
    "E",
    "F",
    "N",
    "Q",
    "W",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
